# Generated by Django 3.2 on 2021-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0006_auto_20210718_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='write_up',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
