# Generated by Django 3.2 on 2021-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0008_auto_20210929_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='write_up',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
